import plotly.graph_objects as go

fig =go.Figure(go.Sunburst(
    labels=["Total",
            "Register File",
            "Arithmetic Logic Unit",
            "Other",
            "Add/Sub",
            "Bit operations",
            "Shifting",
            "Register 1",
            "Register 2",
            "Register 3",
            "Register 4",
            "Register 5",
            "Register 6",
            "Register 7",
            "Program Counter",
            "PC Register 1",
            "PC Register 2",
            "Incrementer",
            "Read0 Multiplexer",
            "Read1 Multiplexer",
            "Result selection",
            "Branching Logic",
            "Control Logic",
            "Datapath Multiplexing",
            "Memory & Clock Logic"
    ],
    parents=["",
             "Total",
             "Total",
             "Total",
             "Arithmetic Logic Unit",
             "Arithmetic Logic Unit",
             "Arithmetic Logic Unit",
             "Register File",
             "Register File",
             "Register File",
             "Register File",
             "Register File",
             "Register File",
             "Register File",
             "Total",
             "Program Counter",
             "Program Counter",
             "Program Counter",
             "Register File",
             "Register File",
             "Arithmetic Logic Unit",
             "Program Counter",
             "Register File",
             "Other",
             "Other"
    ],
    values=[2041,
            1045,
            508,
            164,
            116,
            146,
            179,
            92,
            92,
            92,
            92,
            92,
            92,
            92,
            324,
            92,
            92,
            80,
            163,
            163,
            67,
            60,
            75,
            80,
            84
    ],
    branchvalues="total",
    textinfo='label+value+percent entry'
))
# Update layout for tight margin
# See https://plot.ly/python/creating-and-updating-figures/
fig.update_layout(margin = dict(t=0, l=0, r=0, b=0))
fig.write_image("paper/images/gate_pie_chart.png", width=1024, height=1024, scale=2)